version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=project
    restart: unless-stopped

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - /usr/src/app/static
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
